
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 18 01:37:20 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 6;
  public static final int GRT = 23;
  public static final int GRTEQ = 24;
  public static final int REQ = 21;
  public static final int NUMCONST = 40;
  public static final int LPAREN = 34;
  public static final int SEMI = 32;
  public static final int CONTINUE = 14;
  public static final int LSS = 25;
  public static final int FOR = 13;
  public static final int MINUS = 17;
  public static final int RPAREN = 35;
  public static final int LSSEQ = 26;
  public static final int AND = 27;
  public static final int OR = 28;
  public static final int COMMA = 33;
  public static final int INC = 30;
  public static final int DIV = 19;
  public static final int PLUS = 16;
  public static final int IF = 7;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 29;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MOD = 20;
  public static final int NEQ = 22;
  public static final int IDENT = 43;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int TIMES = 18;
  public static final int LBRACE = 38;
  public static final int ELSE = 5;
  public static final int LSQUARE = 36;
  public static final int ENUM = 4;
  public static final int POINT = 15;
  public static final int READ = 10;
  public static final int CHARCONST = 42;
  public static final int RSQUARE = 37;
  public static final int RBRACE = 39;
  public static final int BOOLCONST = 41;
  public static final int PROG = 2;
  public static final int DEC = 31;
  public static final int PRINT = 9;
}

